In [12]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,KFold
from sklearn import preprocessing


In [13]:
data=pd.read_csv('Student-University (1).csv')
data


34.62365962  78.02469282  0
0     30.286711    43.894998  0
1     35.847409    72.902198  0
2     60.182599    86.308552  1
3     79.032736    75.344376  1
4     45.083277    56.316372  0
..          ...          ... ..
94    83.489163    48.380286  1
95    42.261701    87.103851  1
96    99.315009    68.775409  1
97    55.340018    64.931938  1
98    74.775893    89.529813  1

[99 rows x 3 columns]

In [14]:
x=data.values[:,0:2]

In [15]:
x

array([[30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644],
       [45.08327748, 56.31637178],
       [61.10666454, 96.51142588],
       [75.02474557, 46.55401354],
       [76.0987867 , 87.42056972],
       [84.43281996, 43.53339331],
       [95.86155507, 38.22527806],
       [75.01365839, 30.60326323],
       [82.30705337, 76.4819633 ],
       [69.36458876, 97.71869196],
       [39.53833914, 76.03681085],
       [53.97105215, 89.20735014],
       [69.07014406, 52.74046973],
       [67.94685548, 46.67857411],
       [70.66150955, 92.92713789],
       [76.97878373, 47.57596365],
       [67.37202755, 42.83843832],
       [89.67677575, 65.79936593],
       [50.53478829, 48.85581153],
       [34.21206098, 44.2095286 ],
       [77.92409145, 68.97235999],
       [62.27101367, 69.95445795],
       [80.19018075, 44.82162893],
       [93.1143888 , 38.80067034],
       [61.83020602, 50.25610789],
       [38.7858038 ,

In [16]:
y=data.values[:,2]
y

array([0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
preX=preprocessing.scale(x)

In [20]:
foldings=KFold(n_splits=5)

In [27]:
for train_i,test_i in foldings.split(preX):
    x_train,x_test,y_train,y_test=train_test_split(preX,y,test_size=0.2)
    
epoc=10000
alpha=0.001
b0=0
b1=0
b2=0


x1=x_train[:,0]
x2=x_train[:,1]
while(epoc>0):
    
    
    for i in range(len(x_train)):
        pred=b0+b1*x1[i]+b2*x2[i]
        prediction=1/(1+np.exp(-pred))
        b0=b0+alpha*(y_train[i]-prediction)*prediction*(1-prediction)*1.0
        b1=b1+alpha*(y_train[i]-prediction)*prediction*(1-prediction)*x1[i]
        b2=b2+alpha*(y_train[i]-prediction)*prediction*(1-prediction)*x2[i]
    epoc=epoc-1
    
print(b0,b1,b2)

x3=x_test[:,0]
x4=x_test[:,1]
ypred=[0]*len(x_test)
ylist=[]

for i in range(len(x_test)):
    pred = b0+b1*x3[i]+b2*x4[i]
    ypred[i] = np.round(1/(1+np.exp(-pred)))
    ylist.append(round(ypred[i]))
    
print(y_test)
print(ylist)

score=accuracy_score(y_test,ypred)
print("accuracy is ",score*100)

0.9269313087752592 2.5672503876903976 2.4297425700972966
[0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1.]
[0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
accuracy is  90.0
